apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: z4alg89by-dotnet-basic
  janus-idp.io/tekton: z4alg89by-dotnet-basic
  backstage.io/kubernetes-id: z4alg89by-dotnet-basic
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: z4alg89by-dotnet-basic
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
